### ISSUE TITLE
Contact section

### ISSUE THREAD

**Issue by LauraTechnology** [front-end-by-rimantas/30-grupe-portfolio-daniels#11]
- [x] Background-color;
- [x] Header ("Contact Us.");
- [x] Container with 3 items;
   - icon - logo
   - header h3 - Address, Email, Phone
   - paragraph p - more detailed Adr., Em., Phon.
  
  - [x] form inputs: 
  - Name;
  - Email;
  - Message;
  - Button (''Submit'')
  
  
![contact](https://user-images.githubusercontent.com/86227142/130151749-09738d85-a641-40b3-915a-7e5f1517995f.png)

**Comment by dkeparute** [comment]
Contact section #11
